### ISSUE TITLE
Simplify YAML template properties

### ISSUE THREAD

**Issue by mjaquiery** [UKRN-Open-Research/ukrn-workshop-builder#7]
The YAML 1.2 specification allows for nested objects to allow JSON-like representation:

```yaml
Mark McGwire: {hr: 65, avg: 0.278}
Sammy Sosa: {
    hr: 63,
    avg: 0.288,
    nested: {here: "is", some: "object", with: 4, fields: }
 }
```

The YAML template structure, especially the ukrn_wb stuff, would be much simpler if it used fields with this structure, e.g.:

```yaml
title: {
  display: "Title",
  help: "This is the workshop title. It should succinctly explain the location and topic of the workshop."
  required: true,
  format: "string"
}
workshop_id: {
  display: "Workshop identifer",
  help: "We'll tell you what this is.",
  required: true,
  format: "string",
  validate_regex: "/^[A-Z]{2}_[A-Z]{2}[0-9]{8}_[0-9+]$/"
}
```

The backend will need some updating to fix this, and the templates may also require updating. There is a good chance that this will introduce breaking changes for the workshop builder tool that mean older workshops will not be editable using the workshop builder. Older workshops could either be updated to the new format or newer versions could be version-stamped and older workshops treated as special cases.
